version: '3.8'

services:
  postgres:
    image: postgres
    container_name: soflux-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: soflux
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  redis:
    container_name: soflux-redis
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/var/lib/redis
    restart: unless-stopped
volumes:
  postgres:
  redis-data:
